apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-grpc
  name: helloworld-grpc
spec:
  selector:
    matchLabels:
      app: helloworld-grpc
  template:
    metadata:
      labels:
        app: helloworld-grpc
    spec:
      containers:
      - image: helloworld-grpc:latest
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 50051
          protocol: TCP
          name: grpc
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 50051
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 50051
          initialDelaySeconds: 3
          periodSeconds: 3
