
resources:
- namespace.yaml
- deployment.yaml
- service.yaml

images:
- name: helloworld-grpc
  newName: gcr.io/jkwng-images/helloworld-grpc
  newTag: v2.3

configMapGenerator:
- name: helloworld-grpc-tenant-config
  files:
    - configs/tenant-config.yaml

commonLabels:
  app: helloworld-grpc

namespace: hellogrpc