apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-grpc
  name: helloworld-grpc
spec:
  ports:
  - port: 50051 
    protocol: TCP
    targetPort: 50051
    name: grpc
  selector:
    app: helloworld-grpc
