apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hellogrpc-selfsigned
  namespace: istio-system
spec:
  # Secret names are always required.
  secretName: hellogrpc-tls
  commonName: localhost
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer