
bases: 
- https://github.com/kubernetes-sigs/external-dns/kustomize?ref=v0.12.0

resources:
- namespace.yaml

patchesStrategicMerge:
- serviceaccount.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
  path: deployment-args.yaml


namespace: external-dns