apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hellogrpc-selfsigned
spec:
  # Secret names are always required.
  secretName: hellogrpc-tls
  commonName: hellogrpc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer