apiVersion: v1
kind: Service
metadata:
  annotations:
    controller.autoneg.dev/neg: '{"backend_services":{"50051":[{"name":"hellogrpc-dev-b","max_rate_per_endpoint":1000}]}}'
  name: helloworld-grpc
